[package]
name = "abra_module_ard"
version = "0.0.0"
edition = "2024"
license = "MPL-2.0"

[lib]
crate-type = ["cdylib"]
test = false
[dependencies]
abra_core = { workspace = true }
crossterm = "0.29.0"

[build-dependencies]
abra_core = { workspace = true }
