[book]
authors = ["Anand Dukkipati"]
language = "en"
src = "src"
title = "The Abra Programming Language"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/anandrav/abra"

[output.html.search]
enable = true
